app/views.py
from flask import render_template,Blueprint,request,flash
from flask_login  import current_user,login_required
from data import get_toprated_movies,get_popular_movies,search_movies

core= Blueprint("core", __name__, static_url_path="/static",template_folder="../templates",static_folder="../static")
@core.route('/')
@core.route('/home')
def home():   
    popular =get_popular_movies() 
    top = get_toprated_movies()
    if current_user.is_authenticated:
        favorite_movies=[ movie.movie_id for movie in current_user.favorite_movies]
    else:
        favorite_movies=[]
        
    return render_template("index.html", popular_movies=popular, toprated_movies=top, favorite_movies=favorite_movies)

@core.route('/movies/toprated')
def top_rated_movies():
    from flask import request
    page=int(request.args.get('page', 1)) 
    movies=get_toprated_movies(page)

    page_start_index=max(page-4,1)
    page_end_index=page_start_index+10
    if current_user.is_authenticated :
        favorite_movies=[movie.movie_id for movie in current_user.favorite_movies]
    else:
        favorite_movies=[]
    return render_template('movie_list.html',movies=movies,page=page, page_start_index=page_start_index,page_end_index=page_end_index,favorite_movies=favorite_movies )


@core.route('/movies/popular')
def popular_movies():
    from flask import request
    page=int(request.args.get('page', 1)) 
    movies=get_popular_movies(page)
    page_start_index=max(page-4,1)
    page_end_index=page_start_index+10
    if current_user.is_authenticated :
        favorite_movies=[movie.movie_id for movie in current_user.favorite_movies]
    else:
        favorite_movies=[]
    return render_template('movie_list.html',movies=movies, page=page,page_start_index=page_start_index,page_end_index=page_end_index,favorite_movies=favorite_movies  )




@core.route('/movies/<movie_id>',methods=['GET','POST'])
def movie_detalis(movie_id):
    from data import get_movies_details,get_movies_images,get_movies_recommendations,get_movies_videos
    from users.models import Comment
    from flask_login import current_user
    from .extensions import db
    movie=get_movies_details(movie_id) 
    fetched_videos=get_movies_videos(movie_id)
    images=get_movies_images(movie_id)
    
    recommendations=get_movies_recommendations(movie_id) 

    videos=get_movies_videos(movie_id)
    
    videos = [
        item
        for item in fetched_videos
        if item.get("type") == "Trailer" and item.get("official")
    ]

    if len(videos) > 1:
            video_key = videos[0]["key"]
    elif len(fetched_videos) > 1:
            video_key = fetched_videos[0]["key"]
    else:
            video_key = None
            
    if request.method=="POST":
        content=request.form.get("content")
        if  not content:
            flash  ('Comment content can not be empty! ',"error"   )     
        else:
            comment=Comment(movie_id=movie_id,content=content,user=current_user)
            db.session.add(comment)
            db.session.commit()
   

    comments=Comment.query.filter_by(movie_id=movie_id).all()
    print(comments)
    return render_template('details.html', movie=movie, images=images, recommendations=recommendations,comments=comments,video_key=video_key)

@core.route("/comment/<int:comment_id>/delete", methods=["POST"])
@login_required
def delete_comment(comment_id):
    from users.models import Comment
    from .extensions import db
    from flask import jsonify

    comment = Comment.query.get_or_404(comment_id)

    if current_user.id == comment.user_id:
        db.session.delete(comment)
        db.session.commit()
        return jsonify({"status": "success"}), 200
    else:
        return (
            jsonify(
                {
                    "status": "error",
                    "message": "This comment can be deleted only by it's author!",
                }
            ),
            400,
        )
@core.route("/movies/search")
def search():
    page = int(request.args.get("page", 1))
    query = request.args.get("query", "")
    movies = search_movies(query,page )
    
   
    page_start_index = max(page - 4, 1)
    page_end_index = page_start_index + 10


    return render_template(
        "movie_list.html",
        movies=movies,
        page=page,
        page_start_index=page_start_index,
        page_end_index=page_end_index,
    )

users/views.py
from flask import Blueprint,render_template,redirect,request, jsonify
from flask_login import login_required

users = Blueprint("users", __name__, static_url_path="/static",template_folder="../templates",static_folder="../static")


@users.route("/movies/favorite/<movie_id>", methods=["GET", "POST"])
@login_required
def toggle_favorite_movie(movie_id):
    from flask_login import current_user
    from users.models import FavoriteMovies
    from app.extensions import db
    favorite_movies=FavoriteMovies.query.filter_by(movie_id=movie_id,user=current_user).first()
    if favorite_movies:
        db.session.delete(favorite_movies)
        db.session.commit()

        movies = current_user.favorite_movies
        print(movies)
        return'delected'
    fav_movie = FavoriteMovies(movie_id=movie_id, user=current_user)

    print(fav_movie)
    db.session.add(fav_movie)
    db.session.commit()

  

    return "saved"

@users.route('/register',methods=['Get','Post'])
def register():
    from flask import request,flash
    from app.extensions import db
    from users.models import User

    if request.method =="POST":
        username=request.form.get('username','')
        email=request.form.get('email','')
        password=request.form.get('password','')

        error=False

        user_exists=User.query.filter_by(email=email).first() is not None 
        if user_exists:
            flash  ('User already exists', "error"  )
            error=True
        
        if  len (password)<4:
            flash  ('password should contains minimum 4 characters',"error"   )
            error=True
        if not error:
            
            user=User(username=username,email=email,password=password)
            
            db.session.add(user)
            db.session.commit()

    return render_template('register.html')



@users.route('/login',methods=['Get','Post'])
def login():
    from flask import request,flash,redirect
    from flask_login import login_user
    from .models import User
    if request.method =="POST":
        email=request.form.get('email','')
        password=request.form.get('password','')

        error=False

        user=User.query.filter_by(email=email).first() 
        if  not user:
            flash  ('User with  this email not exists!Check your email and try again!', "error"  )
           
        elif  password != user.password:
            flash  ('Ivalid password ',"error"   )
            
        else:
            login_user(user)
            return redirect("/")
           

    return render_template('register.html')


@users.route("/logout")
@login_required
def logout():
    from flask_login import logout_user
    logout_user()
    return redirect("/")






@users.route("/profile")
@login_required
def profile():
    from flask_login import current_user
    from data import get_movies_details
    favorite_movies=[get_movies_details(movie.movie_id) for movie in current_user.favorite_movies]
    print(favorite_movies)
    return render_template('profile.html',favorite_movies=favorite_movies)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MovieLab</title>
    <link rel="stylesheet" href="/static/css/nullable.css">
    {%block head%}

    {%endblock%}
</head>

<body>


    <nav class="nav">
        <h1 class="nav-title">MovieApp</h1>
        <ul class="nav-links">
           
            <li class="nav-link"><a class="auth-btn" href="{{ url_for('core.home' ) }}">Home</a>     
            </li>
            
              
           
        </ul>
        <form class="nav-search" method="get" 
        action="{{url_for('core.search')}}" 
        autocomplete="off">
            <input type="text" placeholder="SEARCH" name="query">
            <button><img src="/static/images/nav/search 1.png" alt=""></button>
        </form>
        <div class="nav-profile">
           
            <a href="{{url_for('users.profile')}}">
            <img src="/static/images/nav/account.png" alt="">
            </a>
            {% if current_user.is_authenticated %}
            <a class="auth-btn" href="{{ url_for('users.logout' ) }}">Logout</a>
            {% else %}
            <a class="auth-btn" href="{{ url_for('users.register' ) }}">Signup</a>
            {% endif %}   
        </div>
    </nav>
   
    
      
    <div class="container">
        {%block container%}


        {%endblock%}
    </div>

</body>
<footer>
    <div class=footer>
     <h3>x1ter</h3>
    </div> 
 </footer>
</html>

templates/details.html
{%extends "base.html"%}
{%block head%}
<link rel="stylesheet" href="/static/css/style.css">
<link rel="stylesheet" href="/static/css/details.css">
<link rel="stylesheet" href="/static/css/nullable.css">
{%endblock%}
{%block container%}





<div class="movie-header" class="movies-header-link"
    style="background-image: url('https://image.tmdb.org/t/p/original{{movie.backdrop_path}}');">
    <img src="https://image.tmdb.org/t/p/original{{movie.poster_path}}" alt="">
    <div class="movie-header-details">
        <h1>{{movie.title}}</h1>

        <div class="movie-header-text">
            <p>{{movie.release_date}}</p>

            <div class="movie-description-rating">
                <img src="/static/images/image 3.png" alt="">
                <strong>{{movie.vote_average}}</strong>
            </div>
        </div>

        <p class="movie-overview">{{movie.overview}}</p>

    </div>
</div>
<div class="movie-images">
    <div class="carousel-wrapper">
        {% for i in range(1,11) %}
        <input id="slide{{i}}" type="radio" name="controls" {% if i==1 %} checked="checked" {% endif %} />
        {% endfor %}

        {% for i in range(1,11) %}
        <label for="slide{{i}}" class="nav-dot"></label>
        {% endfor %}

        {% for i in range(1,11) %}
        <label for="slide{{i}}" class="left-arrow"> </label>
        {% endfor %}

        {% for i in range(1,11) %}
        <label for="slide{{i}}" class="right-arrow"> > </label>
        {% endfor %}



        <label for="slide1" class="right-arrow"> > </label>


        <div class="carousel">
            <ul>
                {% for i in range(1,11) %}
                <li>
                    <img src="https://image.tmdb.org/t/p/original{{images.backdrops[i].file_path}}" />
                </li>
                {% endfor %}
            </ul>


        </div>
    </div>
</div>


<div class="movies-video">
    <iframe width="1580" height="515" src="https://www.youtube.com/embed/{{video_key}}">
    </iframe>
</div>

<div class="movies">

    {% for movie in recommendations[:5] %}

    <div class="movie">
        <img src="https://image.tmdb.org/t/p/original{{movie.poster_path}}" alt="">
        <h3>{{movie.title}}</h1>
            <p>{{movie.release_date}}</p>
            <div class="movie-description">
                <div class="movie-description-rating">
                    <img src="/static/images/image 3.png" alt="">
                    <strong>{{movie.vote_average}}</strong>
                </div>
                <div class="movie-description-like">
                    {% if current_user.is_authenticated %}
                    {% if movie.id in favorite_movies %}
                    <img class="movie-like" src="/static/images/image 5.png" data-movie-id="{{movie.id}}" alt="">
                    {% else %}
                    <img class="movie-like" src="/static/images/image 4.png" data-movie-id="{{movie.id}}" alt="">
                    {% endif %}
                    {% else %}
                    <a href="/login"><img src="/static/images/image 4.png" alt=""></a>
                    {% endif %}

                </div>
            </div>
    </div>

    ЬТМ

    {% endfor %}
</div>

<div class=comments>
    <h3>Commets</h3>
    <form class="comment_form" autocomplete="off" method="post">
        <textarea name="content" type="text" placeholder="Write you comment:"></textarea>
        {% if current_user.is_authenticated %}

        <button type="submit" class="comment_btn">Send</button>
        {% else %}
        <a href="{{ url_for('users.login' ) }}" class="comment_btn">Send</a>
        {% endif %}
    </form>
</div>

<div class="comments-list">


    {% for comment in comments %}
    <div class="comment-details" id='comment-{{comment.id}}'>
        <div class="comment-details-header">

            <h3>{{comment.user.username}}</h3>
            <div class="comment-details-header-right">
                <p>{{comment.created_at.strftime('%Y-%m-%d')}}</p>
                {% if current_user.is_authenticated %}
                {% if current_user == comment.user %}
                <svg class="comment-delete-btn" data-comment-id="{{comment.id}}" fill="#ff0000" height="30px"
                    width="30px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 330 330" xml:space="preserve"
                    stroke="#ff0000">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <g id="XMLID_6_">
                            <g id="XMLID_11_">
                                <path
                                    d="M240,121.076H30V275c0,8.284,6.716,15,15,15h60h37.596c19.246,24.348,49.031,40,82.404,40c57.897,0,105-47.103,105-105 C330,172.195,290.816,128.377,240,121.076z M225,300c-41.355,0-75-33.645-75-75s33.645-75,75-75s75,33.645,75,75 S266.355,300,225,300z">
                                </path>
                            </g>
                            <g id="XMLID_18_">
                                <path
                                    d="M240,90h15c8.284,0,15-6.716,15-15s-6.716-15-15-15h-30h-15V15c0-8.284-6.716-15-15-15H75c-8.284,0-15,6.716-15,15v45H45 H15C6.716,60,0,66.716,0,75s6.716,15,15,15h15H240z M90,30h90v30h-15h-60H90V30z">
                                </path>
                            </g>
                            <g id="XMLID_23_">
                                <path
                                    d="M256.819,193.181c-5.857-5.858-15.355-5.858-21.213,0L225,203.787l-10.606-10.606c-5.857-5.858-15.355-5.858-21.213,0 c-5.858,5.858-5.858,15.355,0,21.213L203.787,225l-10.606,10.606c-5.858,5.858-5.858,15.355,0,21.213 c2.929,2.929,6.768,4.394,10.606,4.394c3.839,0,7.678-1.465,10.607-4.394L225,246.213l10.606,10.606 c2.929,2.929,6.768,4.394,10.607,4.394c3.839,0,7.678-1.465,10.606-4.394c5.858-5.858,5.858-15.355,0-21.213L246.213,225 l10.606-10.606C262.678,208.535,262.678,199.039,256.819,193.181z">
                                </path>
                            </g>
                        </g>
                    </g>
                </svg>
                {% endif %}
                {% endif %}
            </div>
        </div>


        <p>{{comment.content}}</p>
    </div>

    {% endfor %}
</div>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll(".comment-delete-btn").forEach(button => {
            button.addEventListener("click", function () {
                const commentId = this.getAttribute("data-comment-id");
                const commentElement = document.getElementById("comment-" + commentId);
                if (confirm("Ви впевнені, що хочете видалити цей коментар?")) {
                    fetch(`https://movi-app-ihba.onrender.com/comment/${commentId}/delete`, {
                        method: "POST"
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.status == "success") {
                                commentElement.remove();
                            } else {
                                alert(data.message);
                            }
                        })
                        .catch(error => console.error("Помилка:", error));
                }
            });
        });
    });

</script>
{%endblock%}

templates/index.html
{%extends "base.html"%}
{%block head%}
<link rel="stylesheet" href="/static/css/style.css">
{%endblock%}
{%block container%}    
<div class="movies-header">
    <h2>Top rated movies:</h2>
    <a href="{{ url_for('core.top_rated_movies' ) }}" class="movies-header-link">All</a>
</div>
<div class="movies">

    {% for movie in toprated_movies[:5] %}

    <div class="movie">
        <img src="https://image.tmdb.org/t/p/original{{movie.poster_path}}" alt="">
        <h3>{{movie.title}}</h3>
        <p>{{movie.release_date}}</p>
        <div class="movie-description">
            <div class="movie-description-rating">
                <img src="/static/images/image 3.png" alt="">
                <strong>{{movie.vote_average}}</strong>
            </div>
            <div class="movie-description-like">
                {% if current_user.is_authenticated %}
                    {% if movie.id in favorite_movies %}
                        <img class="movie-like" src="/static/images/image 5.png" data-movie-id="{{movie.id}}" alt="">
                {% else %}
                        <img class="movie-like" src="/static/images/image 4.png" data-movie-id="{{movie.id}}" alt="">
                {% endif %}
                    {% else %}
                        <a href="/login"><img src="/static/images/image 4.png" alt=""></a>
                {% endif %}

            </div>
        </div>
    </div>


    {% endfor %}
</div>

<div class="movies-header">
    <h2>Popular movies:</h2>
    <a href="{{ url_for('core.popular_movies' ) }}" class="movies-header-link">All</a>
</div>
<div class="movies">

    {% for movie in popular_movies[:5] %}

    <div class="movie">
        <img src="https://image.tmdb.org/t/p/original{{movie.poster_path}}" alt="">
        <h3>{{movie.title}}</h3>
        <p>{{movie.release_date}}</p>
        <div class="movie-description">
            <div class="movie-description-rating">
                <img src="/static/images/image 3.png" alt="">
                <strong>{{movie.vote_average}}</strong>
            </div>
            <div class="movie-description-like">
                {% if current_user.is_authenticated %}
                {% if movie.id in favorite_movies %}
                    <img class="movie-like" src="/static/images/image 5.png" data-movie-id="{{movie.id}}" alt="">
            {% else %}
                    <img class="movie-like" src="/static/images/image 4.png" data-movie-id="{{movie.id}}" alt="">
            {% endif %}
                {% else %}
                    <a href="/login"><img src="/static/images/image 4.png" alt=""></a>
            {% endif %}

            </div>
        </div>
    </div>


    {% endfor %}
</div>

<script>
    let buttons = document.querySelectorAll(".movie-like")
    buttons.forEach((btn) => {
        btn.addEventListener('click', () => {
            console.log('click')
            let movie_id = btn.dataset.movieId
            console.log(movie_id)
            let url = `https://movi-app-ihba.onrender.com/movies/favorite/${movie_id}`
            fetch(url)
                .then((res) => {
                    return res.text()
                })
                .then((text) => {
                    console.log(text)
                    if (text.includes('saved')) {
                        btn.src = "/static/images/image 5.png"
                    } else {
                        btn.src = "/static/images/image 4.png"

                    }

                })
        })
    })
</script>
{%endblock%}

templates/movie_list.html
{%extends "base.html"%}
{%block head%}
<link rel="stylesheet" href="/static/css/style.css">
{%endblock%}
{%block container%}

<style>

</style>
</head>

<body>
    <h1>GeeksforGeeks</h1>



    <div class="movies">

        {% for movie in movies%}

        <div class="movie">
            <img src="https://image.tmdb.org/t/p/original{{movie.poster_path}}" alt="">

            <a href="{{ url_for('core.movie_detalis', movie_id=movie.id ) }}">{{movie.title}}</a>
            <p>{{movie.release_date}}</p>
            <div class="movie-description">
                <div class="movie-description-rating">
                    <img src="/static/images/image 3.png" alt="">
                    <strong>{{movie.vote_average}}</strong>
                </div>
                <div class="movie-description-like">
                    {% if current_user.is_authenticated %}
                    {% if movie.id in favorite_movies %}
                    <img class="movie-like" src="/static/images/image 5.png" data-movie-id="{{movie.id}}" alt="">
                    {% else %}
                    <img class="movie-like" src="/static/images/image 4.png" data-movie-id="{{movie.id}}" alt="">
                    {% endif %}
                    {% else %}
                    <a href="/login"><img src="/static/images/image 4.png" alt=""></a>
                    {% endif %}

                </div>
            </div>
        </div>


        {% endfor %}
    </div>

    <div class="page_buttons">
        {% for i in range(page_start_index,page_end_index) %}
        <button {% if page==i %} class="page_btn active" {% else %} class="page_btn" {% endif %}
            onclick="changeMoviesPage('{{i}}')">{{i}}</button>
        {% endfor %}
    </div>




    <script>
        let buttons = document.querySelectorAll(".movie-like")
        buttons.forEach((btn) => {
            btn.addEventListener('click', () => {
                console.log('click')
                let movie_id = btn.dataset.movieId
                console.log(movie_id)
                let url = `https://movi-app-ihba.onrender.com/favorite/${movie_id}`

                fetch(url)
                    .then((res) => {
                        return res.text()
                    })
                    .then((text) => {
                        console.log(text)
                        if (text.includes('saved')) {
                            btn.src = '/static/images/image5.png'
                        } else {
                            btn.src = '/static/images/image 4.png'
                        }
                    })
            })
        })



        function changeMoviesPage(page) {
            const currentParams = new URLSearchParams(window.location.search)
            currentParams.set('page',page)
            window.location.search=currentParams.toString()
        }
    </script>




    {%endblock%}

templates/profile.html
{%extends "base.html"%}
{%block head%}
<link rel="stylesheet" href="/static/css/style.css">
{%endblock%}
{%block container%}

<div class="movies">

    {% for movie in favorite_movies%}
        {%if movie.id%}

    <div class="movie">
        <img src="https://image.tmdb.org/t/p/original{{movie.poster_path}}" alt="">

        <a href="{{ url_for('core.movie_detalis', movie_id=movie.id ) }}">{{movie.title}}</a>
            <p>{{movie.release_date}}</p>
            <div class="movie-description">
                <div class="movie-description-rating">
                    <img src="/static/images/image 3.png" alt="">
                    <strong>{{movie.vote_average}}</strong>
                </div>
                <div class="movie-description-like">
                   
                        <img class="movie-like" src="/static/images/image 5.png" data-movie-id="{{movie.id}}" alt="">
                    
            </div>
        </div>
    </div>
{% endif %}
    {% endfor %}
</div>
<script>
    let buttons = document.querySelectorAll(".movie-like")
    buttons.forEach((btn) => {
        btn.addEventListener('click', () => {
            console.log('click')
            let movie_id = btn.dataset.movieId
            console.log(movie_id)
            let url = `https://movi-app-ihba.onrender.com/home${movie_id}`
            fetch(url)
                .then((res) => {
                    if (res.ok){
                       const movie=btn.parentElement.parentElement.parentElement;
                       movie.remove()
                }
         })
                   
        })
    })
</script>

 {%endblock%}

templates/register.html
{%extends "base.html"%}
{%block head%}
<link rel="stylesheet" href="/static/css/register.css">
<link rel="stylesheet" href="/static/css/style.css">
{%endblock%}
   

    

{%block container%}
   
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="messages">
        {% for category,message in messages %}
        <div class="message {{category}}"> {{message}}
            <svg class="message-cross" width="30px" height="30px" viewBox="0 0 32.00 32.00" fill="none"
                xmlns="http://www.w3.org/2000/svg" stroke="#000000" transform="rotate(90)" stroke-width="2.4">
                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC"
                    stroke-width="0.576"></g>
                <g id="SVGRepo_iconCarrier">
                    <path
                        d="M12 22.75C6.07 22.75 1.25 17.93 1.25 12C1.25 6.07 6.07 1.25 12 1.25C17.93 1.25 22.75 6.07 22.75 12C22.75 17.93 17.93 22.75 12 22.75ZM12 2.75C6.9 2.75 2.75 6.9 2.75 12C2.75 17.1 6.9 21.25 12 21.25C17.1 21.25 21.25 17.1 21.25 12C21.25 6.9 17.1 2.75 12 2.75Z"
                        fill="#000000"></path>
                    <path
                        d="M9.17011 15.58C8.98011 15.58 8.79011 15.51 8.64011 15.36C8.35011 15.07 8.35011 14.59 8.64011 14.3L14.3001 8.63999C14.5901 8.34999 15.0701 8.34999 15.3601 8.63999C15.6501 8.92999 15.6501 9.40998 15.3601 9.69998L9.70011 15.36C9.56011 15.51 9.36011 15.58 9.17011 15.58Z"
                        fill="#000000"></path>
                    <path
                        d="M14.8301 15.58C14.6401 15.58 14.4501 15.51 14.3001 15.36L8.64011 9.69998C8.35011 9.40998 8.35011 8.92999 8.64011 8.63999C8.93011 8.34999 9.41011 8.34999 9.70011 8.63999L15.3601 14.3C15.6501 14.59 15.6501 15.07 15.3601 15.36C15.2101 15.51 15.0201 15.58 14.8301 15.58Z"
                        fill="#000000"></path>
                </g>
            </svg>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>


    <div class="root">
        <div class="main">
            <input type="checkbox" id="chk" aria-hidden="true">

            <div class="signup">
                <form method="post">
                    <label for="chk" aria-hidden="true">Sign up</label>
                    <input type="text" name="username" placeholder="User name" required="">
                    <input type="email" name="email" placeholder="Email" required="">
                    <input type="password" name="password" placeholder="Password" required="">
                    <button type="submit">Sign up</button>
                </form>
            </div>

            <div class="login">
                <form method="post" action="/login">
                    <label for="chk" aria-hidden="true">Login</label>
                    <input type="email" name="email" placeholder="Email" required="">
                    <input type="password" name="password" placeholder="Password" required="">
                    <button>Login</button>
                </form>
            </div>
        </div>
    </div>


    <script>
        const messageButtons = document.querySelectorAll(".message-cross");
        messageButtons.forEach((btn) => {
            btn.addEventListener("click", (e) => {
                //console.log("clicked");
                const message = btn.parentElement;
                message.remove();

            });
        });
    </script>





{%endblock%}